### ISSUE TITLE
Project does not get build.

### ISSUE THREAD

**Issue by mustanshir-soni-grubbrr** [clover/clover-android-sdk#102]
Could not install Gradle distribution from 'https://artifactory.corp.clover.com/artifactory/gradle-distributions/gradle-7.4.2-bin.zip'.
Reason: java.net.SocketTimeoutException: Connect timed out.

![Clover SDK Issue](https://github.com/clover/clover-android-sdk/assets/69785619/909dddb6-b7f2-43a4-813b-a25b6c7c5529)

Thank you for your help.

**Comment by vacagonzalo2** [comment]
same problem

**Comment by mtomko-clover** [comment]
Fixed in latest release, r316
