### ISSUE TITLE
Duplicate and incompatible class PrintJobsTestActivity

### ISSUE THREAD

**Issue by kcfdaniel** [clover/clover-android-sdk#103]
Please delete the file that's not currently in use (the java one), it's not compatible with the layout.  Even after fixing, it'd cause duplicate class error.
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/2148fd60-0d29-48b5-8cbc-4964d5dc13db">

**Comment by mtomko-clover** [comment]
Fixed in latest release, r316
