### ISSUE TITLE
Instruction for target_new_environment

### ISSUE THREAD

**Issue by ahaverty** [clover/clover-android-sdk#28]
The instructions for running target_new_environment are a little ambiguous as a new clover developer.

This guide (https://docs.clover.com/build/android-emulator-setup/) directs a user to this github's readme and source.
It would have been better if the guides indicated that the script should be ran as a .sh on the host machine as opposed to the new genymotion clover environment (obvious now). Along with indication on what dependencies are needed to run the script: install of adb (which isn't automatic with android studio), and connected to new genymotion environment.
A downloadable .sh script would also have sped this step up I believe.
Thank you

**Comment by 1sn0s** [comment]
Adding here:
I was using an older android emulator like Andy. It did not have the perl interpreter and so the script was not running there. 
I deleted the existing "url"  and "target" and inserted corresponding to my target environment, by running the commands. The cleared the application data for clover engine.

**Comment by HariSeldon51** [comment]
I'm afraid I have to agree -- there are really no instructions provided that describe how or where to run this script :( I'm currently stuck at this step trying to figure out how to run it. This part really needs better instructions.

**Comment by jamescha** [comment]
The instructions have been improved to detail that it is a shell script and there is a requirement of having adb within your path.
