### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by javichaques** [clover/clover-android-sdk#56]
Hi,

Which are the rules for proguard?

I try to build release with minify and shrinkResources enabled and this fails with this Warning:

**Warning: com.clover.core.internal.calc.Decimal: can't find referenced class edu.umd.cs.findbugs.annotations.SuppressFBWarnings**

> release {
>     minifyEnabled true
>     shrinkResources true
>     debuggable false
>     proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>     signingConfig signingConfigs.release
> }

**Comment by satur9nine** [comment]
Try adding this to your rules: `-dontwarn edu.umd.cs.findbugs.annotations.SuppressFBWarnings`

**Comment by javichaques** [comment]
It's working, ty!
