### ISSUE TITLE
Can't login using eu credentials, bash script in readme doesn't work on Android 6.0+.

### ISSUE THREAD

**Issue by ConorGarry** [clover/clover-android-sdk#65]
I've registered via eu environment but I can't login on an Android emulator.

I've downloaded the dev apks using the _eu.clover_ url and I've scrubbed through community.clover.com for answers, but they're all out of date. The answers given, like the script in the Readme file in your repo are out of date: `/data/data/com.android.providers.settings/databases/settings.db` has not existed since Androird Marshmallow (6.0), yet the [guide](https://docs.clover.com/clover-platform/docs/setting-up-an-android-emulator) shows that Stations 2018 uses Nougat (7.1.1).

Please advise, thanks.

**Comment by dxcook5** [comment]
Hi @ConorGarry ,

I've updated our docs with a new section ([Update device settings for production testing](https://docs.clover.com/clover-platform/docs/setting-up-an-android-emulator#section--update-device-settings-for-production-testing-)), and I tested the steps with a Station 2018 emulator.  If your emulator is using the EU dev APKs, this should fix the issue.
