### ISSUE TITLE
Payment Connector Example?

### ISSUE THREAD

**Issue by lainz** [clover/clover-android-sdk#74]
Hi, I've followed the steps here
https://docs.clover.com/clover-platform/docs/take-a-payment-with-payment-connector

I've created an application and set the remoteApplicationId as well.

But when I click the button it does nothing. And also from where is supossed to download the file:

> Set the layout to use the provided activity_simple_example.xml file (line 5)

**Comment by morenoh149** [comment]
You could try using an emulator but clover recommends buying a test device. https://docs.clover.com/clover-platform/docs/emulator-hardware-profiles
