### ISSUE TITLE
Missing OrderTestActivity

### ISSUE THREAD

**Issue by jdprajapati** [clover/clover-android-sdk#75]
com.clover.android.sdk.examples.OrderTestActivity

Please check above package path and add activity.

**Comment by matthewcorven** [comment]
@dgutzmann is this missing Activity available in a local branch somewhere, or should it be removed from the manifest?


![image](https://user-images.githubusercontent.com/27839633/93411147-7f0bfa00-f868-11ea-9d22-2f221f2ade27.png)

**Comment by dxcook5** [comment]
@matthewcorven and @jdprajapati, thanks for reporting this. It's been removed from the manifest in version 262.2.
